#!/bin/sh

git a .
git c "bkp"
git checkout -b gh-pages
docker-compose run --rm web yarn build
find . -not -name 'index.html' -not -path '*git*' -not -path '*dist*' -delete
sudo chown -R "$USER:users" ./dist
rm .gitignore
git a .
git commit -m ":boom:"
git push -f origin gh-pages
git checkout master
git branch -D gh-pages
